package com.richard.officenavigation.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table BEACON.
 */
public class Beacon {

    private Long id;
    private long x;
    private long y;
    private long mapid;
    /** Not-null value. */
    private String uuid;
    private int major;
    private int minor;

    public Beacon() {
    }

    public Beacon(Long id) {
        this.id = id;
    }

    public Beacon(Long id, long x, long y, long mapid, String uuid, int major, int minor) {
        this.id = id;
        this.x = x;
        this.y = y;
        this.mapid = mapid;
        this.uuid = uuid;
        this.major = major;
        this.minor = minor;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getX() {
        return x;
    }

    public void setX(long x) {
        this.x = x;
    }

    public long getY() {
        return y;
    }

    public void setY(long y) {
        this.y = y;
    }

    public long getMapid() {
        return mapid;
    }

    public void setMapid(long mapid) {
        this.mapid = mapid;
    }

    /** Not-null value. */
    public String getUuid() {
        return uuid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public int getMajor() {
        return major;
    }

    public void setMajor(int major) {
        this.major = major;
    }

    public int getMinor() {
        return minor;
    }

    public void setMinor(int minor) {
        this.minor = minor;
    }

}
