package com.richard.officenavigation.dao;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;
import de.greenrobot.dao.query.Query;
import de.greenrobot.dao.query.QueryBuilder;

import com.richard.officenavigation.dao.Beacon;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table BEACON.
*/
public class BeaconDao extends AbstractDao<Beacon, Long> {

    public static final String TABLENAME = "BEACON";

    /**
     * Properties of entity Beacon.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property X = new Property(1, long.class, "x", false, "X");
        public final static Property Y = new Property(2, long.class, "y", false, "Y");
        public final static Property Mapid = new Property(3, long.class, "mapid", false, "MAPID");
        public final static Property Uuid = new Property(4, String.class, "uuid", false, "UUID");
        public final static Property Major = new Property(5, int.class, "major", false, "MAJOR");
        public final static Property Minor = new Property(6, int.class, "minor", false, "MINOR");
    };

    private Query<Beacon> iMap_BeaconsQuery;

    public BeaconDao(DaoConfig config) {
        super(config);
    }
    
    public BeaconDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'BEACON' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'X' INTEGER NOT NULL ," + // 1: x
                "'Y' INTEGER NOT NULL ," + // 2: y
                "'MAPID' INTEGER NOT NULL ," + // 3: mapid
                "'UUID' TEXT NOT NULL ," + // 4: uuid
                "'MAJOR' INTEGER NOT NULL ," + // 5: major
                "'MINOR' INTEGER NOT NULL );"); // 6: minor
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'BEACON'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Beacon entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getX());
        stmt.bindLong(3, entity.getY());
        stmt.bindLong(4, entity.getMapid());
        stmt.bindString(5, entity.getUuid());
        stmt.bindLong(6, entity.getMajor());
        stmt.bindLong(7, entity.getMinor());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Beacon readEntity(Cursor cursor, int offset) {
        Beacon entity = new Beacon( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // x
            cursor.getLong(offset + 2), // y
            cursor.getLong(offset + 3), // mapid
            cursor.getString(offset + 4), // uuid
            cursor.getInt(offset + 5), // major
            cursor.getInt(offset + 6) // minor
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Beacon entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setX(cursor.getLong(offset + 1));
        entity.setY(cursor.getLong(offset + 2));
        entity.setMapid(cursor.getLong(offset + 3));
        entity.setUuid(cursor.getString(offset + 4));
        entity.setMajor(cursor.getInt(offset + 5));
        entity.setMinor(cursor.getInt(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Beacon entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Beacon entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "beacons" to-many relationship of IMap. */
    public List<Beacon> _queryIMap_Beacons(long mapid) {
        synchronized (this) {
            if (iMap_BeaconsQuery == null) {
                QueryBuilder<Beacon> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.Mapid.eq(null));
                iMap_BeaconsQuery = queryBuilder.build();
            }
        }
        Query<Beacon> query = iMap_BeaconsQuery.forCurrentThread();
        query.setParameter(0, mapid);
        return query.list();
    }

}
