package com.richard.officenavigation.dao;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.richard.officenavigation.dao.IMap;
import com.richard.officenavigation.dao.INode;
import com.richard.officenavigation.dao.IPath;
import com.richard.officenavigation.dao.IBeacon;
import com.richard.officenavigation.dao.IRssi;
import com.richard.officenavigation.dao.IRssiRaw;
import com.richard.officenavigation.dao.IClusterItem;
import com.richard.officenavigation.dao.ICluster;
import com.richard.officenavigation.dao.INodeCluster;

import com.richard.officenavigation.dao.IMapDao;
import com.richard.officenavigation.dao.INodeDao;
import com.richard.officenavigation.dao.IPathDao;
import com.richard.officenavigation.dao.IBeaconDao;
import com.richard.officenavigation.dao.IRssiDao;
import com.richard.officenavigation.dao.IRssiRawDao;
import com.richard.officenavigation.dao.IClusterItemDao;
import com.richard.officenavigation.dao.IClusterDao;
import com.richard.officenavigation.dao.INodeClusterDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig iMapDaoConfig;
    private final DaoConfig iNodeDaoConfig;
    private final DaoConfig iPathDaoConfig;
    private final DaoConfig iBeaconDaoConfig;
    private final DaoConfig iRssiDaoConfig;
    private final DaoConfig iRssiRawDaoConfig;
    private final DaoConfig iClusterItemDaoConfig;
    private final DaoConfig iClusterDaoConfig;
    private final DaoConfig iNodeClusterDaoConfig;

    private final IMapDao iMapDao;
    private final INodeDao iNodeDao;
    private final IPathDao iPathDao;
    private final IBeaconDao iBeaconDao;
    private final IRssiDao iRssiDao;
    private final IRssiRawDao iRssiRawDao;
    private final IClusterItemDao iClusterItemDao;
    private final IClusterDao iClusterDao;
    private final INodeClusterDao iNodeClusterDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        iMapDaoConfig = daoConfigMap.get(IMapDao.class).clone();
        iMapDaoConfig.initIdentityScope(type);

        iNodeDaoConfig = daoConfigMap.get(INodeDao.class).clone();
        iNodeDaoConfig.initIdentityScope(type);

        iPathDaoConfig = daoConfigMap.get(IPathDao.class).clone();
        iPathDaoConfig.initIdentityScope(type);

        iBeaconDaoConfig = daoConfigMap.get(IBeaconDao.class).clone();
        iBeaconDaoConfig.initIdentityScope(type);

        iRssiDaoConfig = daoConfigMap.get(IRssiDao.class).clone();
        iRssiDaoConfig.initIdentityScope(type);

        iRssiRawDaoConfig = daoConfigMap.get(IRssiRawDao.class).clone();
        iRssiRawDaoConfig.initIdentityScope(type);

        iClusterItemDaoConfig = daoConfigMap.get(IClusterItemDao.class).clone();
        iClusterItemDaoConfig.initIdentityScope(type);

        iClusterDaoConfig = daoConfigMap.get(IClusterDao.class).clone();
        iClusterDaoConfig.initIdentityScope(type);

        iNodeClusterDaoConfig = daoConfigMap.get(INodeClusterDao.class).clone();
        iNodeClusterDaoConfig.initIdentityScope(type);

        iMapDao = new IMapDao(iMapDaoConfig, this);
        iNodeDao = new INodeDao(iNodeDaoConfig, this);
        iPathDao = new IPathDao(iPathDaoConfig, this);
        iBeaconDao = new IBeaconDao(iBeaconDaoConfig, this);
        iRssiDao = new IRssiDao(iRssiDaoConfig, this);
        iRssiRawDao = new IRssiRawDao(iRssiRawDaoConfig, this);
        iClusterItemDao = new IClusterItemDao(iClusterItemDaoConfig, this);
        iClusterDao = new IClusterDao(iClusterDaoConfig, this);
        iNodeClusterDao = new INodeClusterDao(iNodeClusterDaoConfig, this);

        registerDao(IMap.class, iMapDao);
        registerDao(INode.class, iNodeDao);
        registerDao(IPath.class, iPathDao);
        registerDao(IBeacon.class, iBeaconDao);
        registerDao(IRssi.class, iRssiDao);
        registerDao(IRssiRaw.class, iRssiRawDao);
        registerDao(IClusterItem.class, iClusterItemDao);
        registerDao(ICluster.class, iClusterDao);
        registerDao(INodeCluster.class, iNodeClusterDao);
    }
    
    public void clear() {
        iMapDaoConfig.getIdentityScope().clear();
        iNodeDaoConfig.getIdentityScope().clear();
        iPathDaoConfig.getIdentityScope().clear();
        iBeaconDaoConfig.getIdentityScope().clear();
        iRssiDaoConfig.getIdentityScope().clear();
        iRssiRawDaoConfig.getIdentityScope().clear();
        iClusterItemDaoConfig.getIdentityScope().clear();
        iClusterDaoConfig.getIdentityScope().clear();
        iNodeClusterDaoConfig.getIdentityScope().clear();
    }

    public IMapDao getIMapDao() {
        return iMapDao;
    }

    public INodeDao getINodeDao() {
        return iNodeDao;
    }

    public IPathDao getIPathDao() {
        return iPathDao;
    }

    public IBeaconDao getIBeaconDao() {
        return iBeaconDao;
    }

    public IRssiDao getIRssiDao() {
        return iRssiDao;
    }

    public IRssiRawDao getIRssiRawDao() {
        return iRssiRawDao;
    }

    public IClusterItemDao getIClusterItemDao() {
        return iClusterItemDao;
    }

    public IClusterDao getIClusterDao() {
        return iClusterDao;
    }

    public INodeClusterDao getINodeClusterDao() {
        return iNodeClusterDao;
    }

}
