package com.richard.officenavigation.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table IBEACON.
 */
public class IBeacon {

    private Long id;
    private long x;
    private long y;
    private long mapId;
    /** Not-null value. */
    private String uuid;
    private int major;
    private int minor;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public IBeacon() {
    }

    public IBeacon(Long id) {
        this.id = id;
    }

    public IBeacon(Long id, long x, long y, long mapId, String uuid, int major, int minor) {
        this.id = id;
        this.x = x;
        this.y = y;
        this.mapId = mapId;
        this.uuid = uuid;
        this.major = major;
        this.minor = minor;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getX() {
        return x;
    }

    public void setX(long x) {
        this.x = x;
    }

    public long getY() {
        return y;
    }

    public void setY(long y) {
        this.y = y;
    }

    public long getMapId() {
        return mapId;
    }

    public void setMapId(long mapId) {
        this.mapId = mapId;
    }

    /** Not-null value. */
    public String getUuid() {
        return uuid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public int getMajor() {
        return major;
    }

    public void setMajor(int major) {
        this.major = major;
    }

    public int getMinor() {
        return minor;
    }

    public void setMinor(int minor) {
        this.minor = minor;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
