package com.richard.officenavigation.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table ICLUSTER_ITEM.
 */
public class IClusterItem {

    private Long id;
    private long clusterId;
    private int minor;
    private long mapId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public IClusterItem() {
    }

    public IClusterItem(Long id) {
        this.id = id;
    }

    public IClusterItem(Long id, long clusterId, int minor, long mapId) {
        this.id = id;
        this.clusterId = clusterId;
        this.minor = minor;
        this.mapId = mapId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getClusterId() {
        return clusterId;
    }

    public void setClusterId(long clusterId) {
        this.clusterId = clusterId;
    }

    public int getMinor() {
        return minor;
    }

    public void setMinor(int minor) {
        this.minor = minor;
    }

    public long getMapId() {
        return mapId;
    }

    public void setMapId(long mapId) {
        this.mapId = mapId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
