package com.richard.officenavigation.dao;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END
/**
 * Entity mapped to table INODE_CLUSTER.
 */
public class INodeCluster {

    private Long id;
    private long nodeId;
    private int orientation;
    private long clusterId;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    public INodeCluster() {
    }

    public INodeCluster(Long id) {
        this.id = id;
    }

    public INodeCluster(Long id, long nodeId, int orientation, long clusterId) {
        this.id = id;
        this.nodeId = nodeId;
        this.orientation = orientation;
        this.clusterId = clusterId;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public long getNodeId() {
        return nodeId;
    }

    public void setNodeId(long nodeId) {
        this.nodeId = nodeId;
    }

    public int getOrientation() {
        return orientation;
    }

    public void setOrientation(int orientation) {
        this.orientation = orientation;
    }

    public long getClusterId() {
        return clusterId;
    }

    public void setClusterId(long clusterId) {
        this.clusterId = clusterId;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
