package com.richard.officenavigation.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;

import com.richard.officenavigation.dao.IRssiRaw;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table IRSSI_RAW.
*/
public class IRssiRawDao extends AbstractDao<IRssiRaw, Long> {

    public static final String TABLENAME = "IRSSI_RAW";

    /**
     * Properties of entity IRssiRaw.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property NodeId = new Property(1, long.class, "nodeId", false, "NODE_ID");
        public final static Property Minor = new Property(2, int.class, "minor", false, "MINOR");
        public final static Property Orientation = new Property(3, int.class, "orientation", false, "ORIENTATION");
        public final static Property XVal = new Property(4, int.class, "xVal", false, "X_VAL");
        public final static Property YVal = new Property(5, int.class, "yVal", false, "Y_VAL");
        public final static Property MapId = new Property(6, long.class, "mapId", false, "MAP_ID");
    };


    public IRssiRawDao(DaoConfig config) {
        super(config);
    }
    
    public IRssiRawDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists ? "IF NOT EXISTS " : "";
        db.execSQL("CREATE TABLE " + constraint + "'IRSSI_RAW' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'NODE_ID' INTEGER NOT NULL ," + // 1: nodeId
                "'MINOR' INTEGER NOT NULL ," + // 2: minor
                "'ORIENTATION' INTEGER NOT NULL ," + // 3: orientation
                "'X_VAL' INTEGER NOT NULL ," + // 4: xVal
                "'Y_VAL' INTEGER NOT NULL ," + // 5: yVal
                "'MAP_ID' INTEGER NOT NULL );"); // 6: mapId
    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'IRSSI_RAW'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, IRssiRaw entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindLong(2, entity.getNodeId());
        stmt.bindLong(3, entity.getMinor());
        stmt.bindLong(4, entity.getOrientation());
        stmt.bindLong(5, entity.getXVal());
        stmt.bindLong(6, entity.getYVal());
        stmt.bindLong(7, entity.getMapId());
    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public IRssiRaw readEntity(Cursor cursor, int offset) {
        IRssiRaw entity = new IRssiRaw( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getLong(offset + 1), // nodeId
            cursor.getInt(offset + 2), // minor
            cursor.getInt(offset + 3), // orientation
            cursor.getInt(offset + 4), // xVal
            cursor.getInt(offset + 5), // yVal
            cursor.getLong(offset + 6) // mapId
        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, IRssiRaw entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setNodeId(cursor.getLong(offset + 1));
        entity.setMinor(cursor.getInt(offset + 2));
        entity.setOrientation(cursor.getInt(offset + 3));
        entity.setXVal(cursor.getInt(offset + 4));
        entity.setYVal(cursor.getInt(offset + 5));
        entity.setMapId(cursor.getLong(offset + 6));
     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(IRssiRaw entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(IRssiRaw entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
